package com.smile.studio.recipe.model.greendao;

import android.util.Log;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Index;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TYPE".
 */
@Entity
public class Type {

    @Id(autoincrement = true)
    private Long id;

    @Index(unique = true)
    private int pid;
    private String title;

    @Generated
    public Type() {
    }

    public Type(Long id) {
        this.id = id;
    }

    @Generated
    public Type(Long id, int pid, String title) {
        this.id = id;
        this.pid = pid;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getPid() {
        return pid;
    }

    public void setPid(int pid) {
        this.pid = pid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void trace() {
        Log.e("Tag", "id: " + pid + "\ntitle: " + title);
    }
}
